baseURL = "https://claudio-martins.github.io/MRObras/"
languageCode = "pt-pt"
title = "MrObras.pt"
theme = "timer-hugo"
publishDir = "docs"

# Ionicons Icon font são usados oara icones, mais detalhes - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1
[[menu.main]]
name    = "Sobre"
url     = "sobre"
weight  = 2
[[menu.main]]
name    = "Serviços"
url     = "servicos"
weight  = 3
[[menu.main]]
name    = "Galeria de Trabalhos"
url     = "galeriadetrabalhos"
weight  = 4
#[[menu.main]]
#name    = "Blog"
#url     = "blog"
#weight  = 5
[[menu.main]]
name    = "Contactos"
url     = "contactos"
weight  = 5

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "obras casa arranjos pedreiro projeto apartamento"
author = "MROBRAS"
# Google Analitycs
googleAnalitycsID = "Google Analytics ID"
# contact form action
contactFormAction = "#" # esta acção funciona com https://formspree.io

# Secção Banner
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "A REMODELAÇÃO DA SUA CASA COM"
description = "VAMOS FALAR DO SEU NOVO PROJETO"
# botão
btn     = true
btnText = "PEÇA JÁ UM ORÇAMENTO"
btnURL  = "/contactos"

# flip text
[[params.banner.flipText]]
title   = "CREDIBILIDADE"
[[params.banner.flipText]]
title   = "CONFIANÇA"
[[params.banner.flipText]]
title   = "RIGOR"
[[params.banner.flipText]]
title   = "TRANSPARÊNCIA"

# Homepage About Section
[params.about]
enable  = true
title   = "Cuidar da sua casa é a nossa virtude"
image   = "images/sobre/MR obras Logotipo_original-.png"
content = "Com equipas de profissionais especializados, MR.OBRAS.PT apresenta um conjunto de valências integradas, distinguindo-se pelo atendimento e acompanhamento personalizado, exclusividade, profissionalismo e rigor."


# Call to Action
[params.cta]
enable  = true
title   = "VAMOS FALAR SOBRE O SEU PRÓXIMO PROJETO"
content = "Pode preencher diretamente o formulário ou contactar através de email ( geral@mrobras.pt ) ou telefone ( 914 306 548 )."
btnText = "Contacte-nos"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "OS NOSSOS SERVIÇOS"


# social icon
[[params.socialIcon]]
icon = "fb icon-03"
url = "https://www.facebook.com/mrobras.pt"

[[params.socialIcon]]
icon = "in icon-04"
url = "https://www.facebook.com/mrobras.pt"

[[params.socialIcon]]
icon = "icon whatsapp-02"
url = "https://api.whatsapp.com/send?phone=+351968827544"
